src/citofreight/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, contact_view
from vehicles_locations.views import LocationCreateView, LocationView #LocationsListView
from loadings_locations.views import (PickCreateView,
                                      PickView,
                                      DestinationCreateView,
                                      DestinationView)
from profiles.views import logout_view

from django.contrib.auth.views import LoginView


urlpatterns = [
    path('', home_view, name='home-view'),
    path('carriers/', include('carriers.urls')),
    path('senders/', include('senders.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('about/', about_view, name='about-view'),
    path('contact/', contact_view, name='contact-view'),
    path('<str:username>/', include('profiles.urls')),
    path('locations/', include('vehicles_locations.urls')),
    path('senders/<str:user>/', include('loadings.urls')),
    path('senders/<str:user>/loadings/add/create pick/', PickCreateView.as_view(), name='pick-create' ),
    path('senders/<str:user>/loadings/add/create destination/', DestinationCreateView.as_view(), name='destination-create'),
    path('carriers/<str:user>/', include('vehicles.urls')),
    path('carriers/<str:user>/vehicles/<str:vehicle_number>/<int:location_id>/', LocationView.as_view(), name='location-detail'),
]

src/loadings/urls.py
from django.urls import path, include


from loadings.views import (CargoCreateView,
                            CargoView,
                            CargoUpdateView,
                            CargoDeleteView,
                            FindingResultView,
                            VehicleResultView,)

from senders.views import SenderCargoList



app_name = 'loadings'
urlpatterns = [
    path('loadings/', SenderCargoList.as_view(), name='sender-cargo'),
    path('loadings/add/', CargoCreateView.as_view(), name='cargo-create'),
    path('loadings/<int:l_id>/', CargoView.as_view(), name='cargo-detail'),
    path('loadings/<int:l_id>/update/', CargoUpdateView.as_view(), name='cargo-update'),
    path('loadings/<int:l_id>/delete/', CargoDeleteView.as_view(), name='cargo-delete'),
    path('loadings/<int:l_id>/result/', FindingResultView.as_view(), name='transport-result'),
    path('loadings/<int:l_id>/result/<str:vehicle_number>/', VehicleResultView.as_view(), name='result-detail'),
    # path('loadings/<int:l_id>/result/<str:vehicle_number>/<str:carrier_name>', CarrierResultView.as_view(), name='deepresult-detail'),


]

src/profiles/urls.py
from django.urls import path


from .views import ProfileDetailView

app_name = 'profiles'
urlpatterns = [
path('', ProfileDetailView.as_view(), name='profile-detail'),


]

src/senders/urls.py
from django.urls import path, include


from senders.views import (SenderCreateView,
                           SenderListView,
                           SenderView,
                           SenderDeleteView,
                           SenderUpdateView)




app_name = 'senders'
urlpatterns = [
    path('', SenderListView.as_view(), name='sender-list'),
    path('create/', SenderCreateView.as_view(), name='sender-create'),
    path('<str:user>/', SenderView.as_view(), name='sender-detail'),
    path('<str:user>/delete/', SenderDeleteView.as_view(), name='sender-delete'),
    path('<str:user>/update/', SenderUpdateView.as_view(), name='sender-update'),

]


# SenderCargoList

src/loadings/models.py
from django.conf import settings
from django.db import models
from senders.models import SenderModel
from loadings_locations.models import LoadingsLocationsModel, LoadingsDestinationModel

User = settings.AUTH_USER_MODEL

class LoadingsModel(models.Model):
    Neutral = 'Neutral'
    FMCG    = 'FMCG'
    ADR     = 'ADR'
    TYPES = (
        (Neutral, 'Neutral'),
        (FMCG,       'FMCG'),
        (ADR,    'Chłodnia'),
    )
    user        = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    pick_date   = models.DateTimeField(blank=False, null=True)
    delivery_date = models.DateTimeField(blank=False, null=True)
    title       = models.CharField(max_length=40)
    types       = models.CharField(max_length=40, choices=TYPES, default=Neutral)
    length      = models.PositiveIntegerField()
    width       = models.PositiveIntegerField()
    high        = models.PositiveIntegerField()
    weight      = models.PositiveIntegerField()
    description = models.TextField(blank=True)
    pick        = models.ForeignKey(LoadingsLocationsModel, on_delete=models.CASCADE, default=True)
    destination = models.ForeignKey(LoadingsDestinationModel, on_delete=models.CASCADE, default=False)



    def load_type(self):
        return self.TYPES in (self.type)


    def __str__(self):
        return "%s %s" % (self.title, self.types)


# Create your models here.
from django.db import models

# Create your models here.

src/loadings/forms.py
from django import forms

from .models import LoadingsModel

from carriers.models import Carrier

class CargoForm(forms.ModelForm):
    Neutral = 'Neutral'
    FMCG    = 'FMCG'
    ADR     = 'ADR'
    TYPES = (
        (Neutral,   'Neutral'),
        (FMCG,      'FMCG'),
        (ADR,       'ADR'),
    )
    pick_date   = forms.SplitDateTimeField(label='Pick Date', widget=forms.SplitDateTimeWidget)
    delivery_date   = forms.SplitDateTimeField(label='Delivery Date', widget=forms.SplitDateTimeWidget)
    title       = forms.CharField(max_length=40)
    types       = forms.ChoiceField(label='Type', choices=TYPES)
    length      = forms.IntegerField(label='Length', widget=forms.TextInput(attrs={"placeholder": "cm" }))
    width       = forms.IntegerField(label='Width', widget=forms.TextInput(attrs={"placeholder": "cm"}))
    high        = forms.IntegerField(label='High', widget=forms.TextInput(attrs={"placeholder": "cm"}))
    weight      = forms.IntegerField(label='Weight', widget=forms.TextInput(attrs={"placeholder": "kg"}))
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'rows':10}))



    class Meta:
        model = LoadingsModel
        fields = [
            'pick_date',
            'delivery_date',
            'pick',
            'destination',
            'title',
            'types',
            'length',
            'width',
            'high',
            'weight',
            'description',
        ]

src/loadings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from .models import LoadingsModel
from .forms import CargoForm
from django.views import View
from django.views.generic import ListView
from carriers.models import Carrier
from vehicles.models import Fleet
from django.db.models import Q



class CargoCreateView(LoginRequiredMixin, View):
    template_name = "loadings/cargo_create.html" # DetailView
    def get(self, request, *args, **kwargs):
        # GET method
        form = CargoForm()
        context = {"form": form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # POST method
        form = CargoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            form = CargoForm()
            return redirect('../')
        context = {"form": form}
        return render(request, self.template_name, context)

class CargoView(View):
    template_name = "loadings/cargo_detail.html" # DetailView
    def get(self, request, l_id, *args, **kwargs):
        # GET method
        context = {}
        if l_id is not None:
            obj = get_object_or_404(LoadingsModel, id=l_id)
            context['object'] = obj
        return render(request, self.template_name, context)


class CargoUpdateView(LoginRequiredMixin, View):
    template_name = "loadings/cargo_update.html" # DetailView
    def get_object(self):
        l_id = self.kwargs.get('l_id')
        obj = None
        if l_id is not None:
            obj = get_object_or_404(LoadingsModel, id=l_id)
        return obj

    def get(self, request, l_id, *args, **kwargs):
        # GET method
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = CargoForm(instance=obj)
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, l_id,  *args, **kwargs):
        # POST method
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = CargoForm(request.POST, instance=obj)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()                
                form = CargoForm()
                return redirect('../')
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)


class CargoDeleteView(LoginRequiredMixin, View):
    template_name = "loadings/cargo_delete.html" # DetailView
    def get_object(self):
        l_id = self.kwargs.get('l_id')
        obj = None
        if l_id is not None:
            obj = get_object_or_404(LoadingsModel, id=l_id)
        return obj

    def get(self, request, l_id, *args, **kwargs):
        # GET method
        context = {}
        obj = self.get_object()
        if obj is not None:
            context['object'] = obj
        return render(request, self.template_name, context)

    def post(self, request, l_id,  *args, **kwargs):
        # POST method
        context = {}
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('../../')
        return render(request, self.template_name, context)


class FindingResultView(View):
    template_name = "loadings/results.html"
    queryset = Fleet.objects.all()
    # queryset = Carrier.objects.all()
    """docstring for FindingResultView"""
    def get_queryset(self):
        return self.queryset

    def get_object(self):
        l_id = self.kwargs.get('l_id')
        obj = None
        if l_id is not None:
            obj = get_object_or_404(LoadingsModel, id=l_id)
        return obj

    def get(self, request, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            c_loc = obj.pick.city
            width = obj.width
            high = obj.high
            length = obj.length
            weight = obj.weight
            forwarders_list = Fleet.objects.filter(Q(location__city__iexact=c_loc) &
                                                             Q(width__gte=width) &
                                                             Q(high__gte=high) &
                                                             Q(length__gte=length) &
                                                             Q(capacity__gte=weight))
            context = {'object_list': forwarders_list}
        return render(request, "loadings/results.html", context)

class VehicleResultView(View):
    template_name = "loadings/results_detail.html" # DetailView
    def get(self, request, vehicle_number, *args, **kwargs):
        # GET method
        context = {}
        if vehicle_number is not None:
            obj = get_object_or_404(Fleet, register=vehicle_number)
            context['object'] = obj
        return render(request, self.template_name, context)


# class CarrierResultView(View):
#     template_name = "loadings/results_carrier.html"
#     def get(self, request, carrier_name, *args, **kwargs):
#         context = {}
#         if carrier_name is not None:
#             obj = get_object_or_404(Carrier, Name=carrier_name)
#             context['object'] = obj
#         return render(request, self.template_name, context)

       

""" Teraz muszę zdefiniowac pozostałe parametry i poprzez .exclude dodać kolejne stopnie filtrowania"""

    # class VehicleListView(View):
    #     template_name = "vehicles/cargo_list.html"
    #     queryset = Fleet.objects.all()
    #
    #     def get_queryset(self):
    #         return self.queryset
    #
    #     def get(self, request, *args, **kwargs):
    #         context = {'object_list': self.get_queryset()}
    #         return render(request, self.template_name, context)

# class SenderListView(ListView):
#     template_name = "senders/senders_list.html"
#     queryset = SenderModel.objects.all()

#     def sender_list_view(request, *args, **kwargs):
#         queryset = SenderModel.objects.all()
#         context = {
#             "object_list": queryset
#         }
#         return render(request, "senders/senders_list.html", context)


# class CarrierVehicleList(ListView):
#     template_name = "vehicles/vehicle_list.html"

#     def get_queryset(self):
#         self.carriers = get_object_or_404(Carrier, Name=self.kwargs['carrier_name'])
#         return Fleet.objects.filter(carriers=self.carriers)

# # Create your views here.

# >>> Entry.objects.filter(
# ...     headline__startswith='What'
# ... ).exclude(
# ...     pub_date__gte=datetime.date.today()
# ... ).filter(
# ...     pub_date__gte=datetime.date(2005, 1, 30)
# ... )

src/loadings/templates/loadings/cargo_create.html
{% extends 'base.html' %}

{% block content %}

<p> <a href="../">Back</a> </p>
<hr/>
<h3><b>Enter your load</b></h1>
<hr/>
<p><a href="create pick">Add pick address |</a><a href="create destination">| Add destination address</a></p>
<form action="." method="post">{% csrf_token %}
	<hr/>
{{ form.as_p }}
<hr/>
<input type="submit" value="Save">
</form>

{% endblock %}

src/loadings/templates/loadings/cargo_delete.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="post">{% csrf_token %}
    <h1>Do you want to delete this cargo from your cargo list list? "{{ object.title }}?"</h1>
    <p><input type="submit" value="Yes"/> <a href="../">Cancel</a> </p>
</form>

{% endblock %}

src/loadings/templates/loadings/cargo_detail.html
{% extends 'base.html' %}

{% block content %}
<p> <a href="../">Back </a> <a href="result"><b> |Find Transport|</b></a></p>
<hr/>
<h1>{{ object.title }}</h1>
<h2>{{ object.type }}</h2>
<h5><b>Pick date:</b> <small>{{ object.pick_date }}</small></h5>
<h5><b>Delivery date:</b> <small>{{ object.delivery_date }}</small></h5>
<hr/>
<p><b>Length: </b>{{ object.length }}cm</p>
<p><b>Width: </b>{{ object.width }}cm</p>
<p><b>High: </b>{{ object.high }}cm</p>
<p><b>Weight: </b>{{ object.weight }}kg</p>
<p><b>Description: </b>{{ object.description }}</p>
<hr/>
<h5><b>Pick: </b> <small>{{ object.pick }}</small></h5>
<h5><b>Destination: </b> <small>{{ object.destination }}</small></h5>
<hr/>
<p> <a href="update">Update |</a><a href="../add">| Add another |</a><a href="delete">| Delete</a> </p>

{% endblock %}

src/loadings/templates/loadings/cargo_list.html
{% extends 'base.html' %}

{% block content %}

<p> <a href="../">Back |</a> <a href="add">| Add</a> </p>
<hr/>
{% if user.loadingsmodel_set.all.exists %}
{% for instance in object_list %}
    <h3><ul><a href="{{ instance.id }}">{{ instance.title }} {{ instance.type }}</a></ul></h3>
{% endfor %}

{% else %}
<p class="lead">Loadings queryset is empty</p>
{% endif %}

{% endblock %}

src/loadings/templates/loadings/cargo_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Enter your load</h1>
<!-- <p><a href="create pick">Add pick address</a> </p>
<p><a href="create destination">Add destination address</a> </p> -->
<form method="post">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Add">
</form>

{% endblock %}

src/loadings/templates/loadings/results.html
{% extends 'base.html' %}

{% block content %}

<p> <a href="../">Back |</a>
<hr/>
<ul>
{% for instance in object_list %}
    <h4><ul><a href="{{ instance.register }}">{{ instance.register }} {{ instance.make }} {{ instance.model }}</a></ul></h4>
{% empty %}
	<p class="lead">There are no trucks in this location</p>
{% endfor %}
</ul>

{% endblock %}

src/loadings/templates/loadings/results_carrier.html
{% extends 'base.html' %}

{% block content %}
<p><a href="../">Back</a> </p>
<h1><b>{{ object.Name }}</b></h1>
<p>Country: {{ object.Country }}</p>
<p>City: {{ object.City }}</p>
<p>Postal Code: {{ object.PostalCode }}</p>
<p>Street: {{ object.Street }}
{{ object.HouseNumber }}</p>
<p>e-mail: {{ object.Email }}</p>
<p>Start Date: {{ object.StartDate }}</p>


{% endblock %}

src/loadings/templates/loadings/results_detail.html
{% extends 'base.html' %}

{% block content %}
<p> <a href="../">Back |</a> <a href="{{ object.location_id }}">| Location</a> </p>
<hr/>
<h2>{{ object.make }} {{ object.model }} | {{ object.register }}</h2>
<hr/>
<h2><b><a href='{% url "profiles:profile-detail" username=object.user %}'>{{ object.user }}</a></b></h2>
<p><b>POWER: </b>{{ object.power }}KM</p>
<p><b>LENGTH: </b>{{ object.length }}cm</p>
<p><b>WIDTH: </b>{{ object.width }}cm</p>
<p><b>HIGH: </b>{{ object.high }}cm</p>
<p><b>CAPACITY: </b>{{ object.capacity }}kg</p>
<h2><b>TYPE: </b>{{ object.types }}</h2>

{% endblock %}